### ISSUE TITLE
Mobile에서 BlackHanSans 웹폰트가 적용 안됨

### ISSUE THREAD

**Issue by beomjinu** [beomjinu/lifeisegg_v2#1]

**Comment by beomjinu** [comment]
NotoSans는 적용되는지 체크

**Comment by beomjinu** [comment]
모바일 문제가 아니고 다른 pc에서도 적용안되는걸 확인. 수정필요

**Comment by beomjinu** [comment]
SpoqaHanSans 폰트 적용에 윗줄 오류가 존재해 아래 코드가 실행 안되었던것.
그러나 왜 맥북(개발환경) 에서는 폰트가 정상이였는지는 모르겠음.
```css
@import url('https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap');
@import url("//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css");
@import url('https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Noto+Sans+KR&display=swap');

@font-face {
    font-family: 'LeeSeoyun';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2202-2@1.0/LeeSeoyun.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
    
.SpoqaHanSans {
    font-family: "Spoqa Han Sans Neo", "sans-serif";
}

.LeeSeoyun {
    font-family: "LeeSeoyun"
}

.BlackHanSans {
    font-family: 'Black Han Sans', sans-serif;
}

.NotoSans {
    font-family: 'Noto Sans KR', sans-serif;
}
```
